### PR TITLE
Issue 4 solved in cpp

### LINKED ISSUE #4: Write a program to print Nth even number

### PR DESCRIPTION
**Pull request by destroyer5067**
Added C++ solution for printing nth even number
and updated contributors.md  file

closes #4

### CODE REVIEW

**Comment by destroyer5067** [comment]
@Almond65  you can review the PR

**Comment by destroyer5067** [comment]
Also this repo is not participating in the hactoberfest2k22?

**Comment by Almond65** [comment]
@destroyer5067 Its participating

**Comment by Almond65** [comment]
the participating repo should only have **hacktoberfest** name in it atleast and the accepted pr s have to be marked **hacktoberfest-accepted**

**Pull request merged**
